### ISSUE TITLE
allow shell commands within interactive CLI

### ISSUE THREAD

**Issue by ssomnath** [ORNL/DataFed#575] opened 2020-12-29 17:55 UTC
How about adding a new "shell" click command? Anything past "shell" would simply executed as is in shell?

For example someone could simply do ``shell ls`` or ``shell mkdir blah`` while within DataFed.

**Comment by dvstans** [comment] 2021-01-29 18:02
Closing - duplicate of #539

**Closed by dvstans** 2021-01-29 18:02 UTC
Labels: New Feature
